### ISSUE TITLE
[BUG] +CME ERROR: 58

### ISSUE THREAD

**Issue by mei-rune** [warthog618/modem#18]
2023/07/31 15:07:36 w:

023/07/31 15:07:36 w: ATZ
2023/07/31 15:07:36 r:
OK
2023/07/31 15:07:36 w: ATE0
2023/07/31 15:07:36 r: ATE0

OK
2023/07/31 15:07:36 w: AT+GCAP
2023/07/31 15:07:36 r:
+CME ERROR: 58
2023/07/31 15:07:36 CME Error: 58

**Comment by warthog618** [comment]
Ok, so your modem throws a CME error 58 in response to +GCAP.
What corrective action do you suggest?

**Comment by warthog618** [comment]
To be clear, this issue is not a bug in the modem library.
There is nothing the library is doing or can do to make the modem return that error - that is from the modem itself.
You provide no information as to how you produce this error or what output you expect or what modem you are using, so not sure what I can add.
